language: php

php:
    - 5.4

before_script:
    - composer install --dev
    - ln -nfs ./vendor/phpunit/phpunit/composer/bin/phpunit ./phpunit
    - php ./travis.setup.php

script: ./phpunit --verbose --coverage-text
