language: php

php:
    - 5.4

before_script:
    - composer install --dev
    - ln -nfs ./vendor/phpunit/phpunit/composer/bin/phpunit ./phpunit
    - ldconfig -v
    - sudo apt-get remove --purge -y libmemcached-dev libmemcached
    - sudo apt-get install libcloog-ppl0
    - wget -c 'http://launchpad.net/libmemcached/1.0/1.0.14/+download/libmemcached-1.0.14.tar.gz'
    - tar -xvf libmemcached-1.0.14.tar.gz
    - sh -c "cd libmemcached-1.0.14 && sudo ./configure --disable-sasl && sudo make all && sudo make install && sudo ldconfig"
    - php ./travis.setup.php
    - sudo ldconfig -v
    - phpenv rehash
    
script: ./phpunit --verbose --coverage-text
